spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Praveen$96
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
